name: MiscPlugin
version: "1.0"
main: "sharkbound.spigot.miscplugin.MiscPlugin"
api-version: "1.13"

commands:
  everblaze:
    description: gives the caller a everblaze
  s:
    description: quick shutdown command
  shulkerwand:
    description: give the caller a shulker spawner wand
  shulkerportal:
    description: give the caller a shulker portal wand
  phantomportal:
    description: summons a horde of phantoms to attack your target
  wand:
    description: gives the caller a wand
