sky_island_schematic: plugins/WorldEdit/schematics/sky.schematic
cow_spawn_egg_name: "&dBetty"
payment_on_kill: 5
currency_name: coins

item_costs:
  ember_rod: 15
  aspect_of_the_end: 20
  mobile_bank: 10

item_settings:
  aspect_of_the_end_range: 60
  aspect_of_the_end_wall_y_autocorrect: 4
  mobile_bank_skull_owner_uuid: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk4ZGY0MmY0NzdmMjEzZmY1ZTlkN2ZhNWE0Y2M0YTY5ZjIwZDljZWYyYjkwYzRhZTRmMjliZDE3Mjg3YjUifX19"

cooldowns:
  aspect_of_the_end: 5
  ember_rod: 5
  mobile_bank: 5

