name: SkyBlock
version: "1.0"
main: sharkbound.spigot.skyblock.plugin.SkyBlock

commands:
  skyblock:
    aliases: [sb]
    description: skyblock super commmand

  s:
    description: stops the server

  listworlds:
    description: list all worlds

  dtp:
    description: dimentional teleport

  test:
    description: debug