name: skyblock
version: "1.0"
main: sharkbound.spigot.skyblock.plugin.SkyBlock

commands:
  skyblock:
    aliases: [sky]
    description: skyblock super commmand
  s:
    description: stops the server
